In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("nlp_test.csv")

In [3]:
df

text  target  \
0     I am a little confused on all of the models of...       7   
1     I'm not familiar at all with the format of the...       5   
2                                   \nIn a word, yes.\n       0   
3     \nThey were attacking the Iraqis to drive them...      17   
4     \nI've just spent two solid months arguing tha...      19   
...                                                 ...     ...   
7527  \n   Henry, if I read you correctly, you may b...      14   
7528  about\nthem on\n\nActually, I thought Macs wer...       4   
7529  I sent a version of this post out a while ago,...       9   
7530  I have this kit which includes the following :...       6   
7531  \nFine, but one of the points of this entire d...      15   

                    category  
0                  rec.autos  
1             comp.windows.x  
2                alt.atheism  
3      talk.politics.mideast  
4         talk.religion.misc  
...                      ...  
7527               sci.space  
7528   comp.sys.mac.hardware  
7529      rec.sport.baseball  
7530            misc.forsale  
7531  soc.religion.christian  

[7532 rows x 3 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7532 entries, 0 to 7531
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   text      7370 non-null   object
 1   target    7532 non-null   int64 
 2   category  7532 non-null   object
dtypes: int64(1), object(2)
memory usage: 176.7+ KB


In [5]:
df['category'].unique()

array(['rec.autos', 'comp.windows.x', 'alt.atheism',
       'talk.politics.mideast', 'talk.religion.misc', 'sci.med',
       'soc.religion.christian', 'comp.graphics',
       'comp.os.ms-windows.misc', 'rec.motorcycles',
       'comp.sys.mac.hardware', 'misc.forsale', 'talk.politics.guns',
       'sci.space', 'comp.sys.ibm.pc.hardware', 'sci.crypt',
       'rec.sport.baseball', 'rec.sport.hockey', 'talk.politics.misc',
       'sci.electronics'], dtype=object)

In [10]:
print(df.iloc[0,0])
print(df.iloc[0,2])

I am a little confused on all of the models of the 88-89 bonnevilles.
I have heard of the LE SE LSE SSE SSEI. Could someone tell me the
differences are far as features or performance. I am also curious to
know what the book value is for prefereably the 89 model. And how much
less than book value can you usually get them for. In other words how
much are they in demand this time of year. I have heard that the mid-spring
early summer is the best time to buy.
rec.autos


In [12]:
print(df.iloc[1,0])
print(df.iloc[1,2])

I'm not familiar at all with the format of these "X-Face:" thingies, but
after seeing them in some folks' headers, I've *got* to *see* them (and
maybe make one of my own)!

I've got "dpg-view" on my Linux box (which displays "uncompressed X-Faces")
and I've managed to compile [un]compface too... but now that I'm *looking*
for them, I can't seem to find any X-Face:'s in anyones news headers!  :-(

Could you, would you, please send me your "X-Face:" header?

I *know* I'll probably get a little swamped, but I can handle it.

	...I hope.
comp.windows.x


In [ ]:
# convert text to numerical : using CoutVectorizer

d1 = "I love programming"
d2 = "programming is interesting"
d3 = "I love biryani very very much"
vocab = {"I","love","programming","is", "interesting","biryani","very","much"}
d1 = [1,1,1,0,0,0,0,0]
d2 = [0,0,1,1,1,0,0,0]
d3 = [1,1,0,0,0,0,1,2,1]


In [27]:
from sklearn.feature_extraction.text import CountVectorizer

d1 = "I love programming"
d2 = "programming is interesting"
d3 = "I love biryani very very much"
documents = [d1,d2,d3]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)
print(vectorizer.vocabulary_)
print(X.toarray())


{'love': 3, 'programming': 5, 'is': 2, 'interesting': 1, 'biryani': 0, 'very': 6, 'much': 4}
[[0 0 0 1 0 1 0]
 [0 1 1 0 0 1 0]
 [1 0 0 1 1 0 2]]
